version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/app/src

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: sh -c 'ngrok authtoken $$NGROK_AUTH && ngrok http flask-app:5000'
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
    depends_on:
      - flask-app
